### ISSUE TITLE
NOMBRE CONCRETO Y DNI

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#10]
# **NOMBRE COMPLETO Y DNI**

Para poder incluirlo en el documento poned por aquí vuestro nombre completo y DNI

Juan Casado Ballesteros 

@Zaedlen @UndMe @daniel-diazl @pablopg99

**Comment by pablopg99** [comment]
Pablo Pardo García. DNI: 09074286G

**Comment by UndMe** [comment]
Jorge Garcia Garcia 
DNI:09073317R

**Comment by UndMe** [comment]
Chicos he tenido que editar los DNIS de los que escribimos en este hilo porque el profesor nos ha comentado que ponerlos en un sitio publico no era lo correcto. 

En resumen, que no le ha gustado asique los he borrado y listo.
@JuanCasado @pablopg99 @Zaedlen
