### ISSUE TITLE
Corrección del documento del videojuego.

### ISSUE THREAD

**Issue by pablopg99** [TecnologiaVideojuegos/proyecto-videojuego-team6#11]
Puesto que no hemos encontrado el archivo .docx para poder editar el documento de diseño actual, adjuntamos un documento de texto con los punto que tenemos que mejorar y algunas ideas de como hacerlo.
El archivo esta subido en Documentación/Diseño y mecánicas a nombre de CORRECCION DOCUMENTO DISEÑO.docx

El profesor nos ha dicho que los DNIs no son necesarios, asi que podeis eliminarlos del documento de diseño final.

**LOS CAMBIOS SE TIENEN QUE REALIZAR HOY PARA TENERLO LISTO ANTES DE LAS 12.**

@Zaedlen @JuanCasado @UndMe

**Comment by JuanCasado** [comment]
Ya está realizada la modificación acorde con lo que habéis detallado, en realidad lo que aparentemente faltaba en el apartado de objetivo estaba contado más abajo en el de niveles.
Lo he modificado incluyendo más detalles y haciendo referencia a ese apartado así como he hecho el justificado.
El documento .docx estaba en la misma carpeta pero con el nombre DESING.docx

Mirad porfa si está todo bien @pablopg99 @UndMe @Zaedlen @daniel-diazl 

Notifico al profesor que se han realizado las modificaciones que sugirió @dfbarrero

**Comment by Zaedlen** [comment]
No estoy contento con la modificación del documento. Habéis visto el documento en clase y por eso os ha dicho eso el  profe?
1. En cualquier caso muchas de las cosas ya estaban explicadas y suena redundante. Repetis todo el rato lo mismo.
2. Además, lo que habéis puesto en objetivo no es el objetivo del juego: ver el mapa completo no es el objetivo, como mucho va en el apartado niveles
3. Más adelante ya digo que el juego será tipo arcade y cómo se jugará la partida. No puse explicitamente lo de los bosses porque no se si al final los habrá como tal. Me explico: un boss es un enemigo diferente a los anteriores con mecánicas nuevas y una dificultad elevada que, en el instante del juego en el que aparece representa un reto para el jugador. Creí que solo íbamos a poner enemigos con el sprite ligeramente más grande y algo más de vida. Pero bueno, lo dejamos así.
4. lo del movimiento lateral también estaba en el documento, por cierto.

En fin, lo he leído, he corregido alguna cosilla que no me ha terminado de gustar y procedo también a actualizar el pdf de la página, que mucho jiji jaja pero nadie lo ha cambiado.
He borrado también los dni´sde la portada, que también podían verse en un sitio publico.

Por ultimo, estas cosas no deberían decirse a ultima hora, y encima pasar por encima de mi y empezar a poner cosas en la corrección sin haberse leído el documento en si. Vale que me pusierais en la issue, pero eso solo lo veo cuando abro github, no tengo forma de recibir una notificación directa. Y está tarde he estado apartado del pc por motivos personales. No se, para situaciones asi tan de emergencia, a las malas se envía un whatsapp para decirme que lo mire. Que porque me ha dado por asomarme ahora tan tarde, si no ya lo veo mañana o pasado xd

**Comment by JuanCasado** [comment]
Lo siento si no llegas a entender lo que significa equipo, porque eso de pasar por cima de ti me parece un poco fuerte, es un documento que expresa las ideas que hemos tenido todos a cerca del videojuego y como pensamos hacerlo y porque lo hayas redactado tú y le hayas puesto tu historia no lo vuelve intocable para el resto.
La finalidad del documento es hacernos pensar sobre el juego y que el profe pueda entender de qué va, si para ello hay que repetir alguna cosa en el apartado de objetivo porque es lo que les ha dicho en clase se repite que tampoco es tan grave, además como objetivo puedes entender ta motivación del personaje como lo que en un nivel tienes que hacer para poder superarlo y él esperaba encontrar esto último, no un set de chistes malos sobre las motivaciones de Diana.
El pdf si estaba modificado, es cierto que los dni no se habían retirado pero puedes ver los commit para comprobarlo.
Puedes también configurar para que de las issues te llegue un correo al teléfono lo cual te evitaría tener que entrar a gitHub para ver estas cosas, es una buena idea.

Me repito porque hay veces que es necesario para que las cosas queden claras, esto es un equipo y nadie pasa por encima de nadie, las cosas se ponen en común, se hablan y vamos avanzando así, sinceramente, me parece muy feo tanto el mensaje, si querías cambiar algo lo haces lo notificas pero te ahorras los malos modos y más aún cuando estás jugando con la fecha de entrega y ni es para tanto, un poco de compañerismo y esas cosas sabes.

@Zaedlen
