### ISSUE TITLE
Programación

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#12]
Puedes subir el ejemplo que hiciste el otro día de los sprites, es por no andarlo mirando jajajaj
@Zaedlen

**Comment by JuanCasado** [comment]
Para calcular los tamaños de cualquier cosa hazlo en función de el ancho y el ato de la pantalla, los puedes obtener con Gama.getX() y Game.getY() que son static, nada de dimensiones a pelo
@Zaedlen

**Comment by JuanCasado** [comment]
Cómo llevas lo de la generación del mapa, se me ocurre que si lo de hacer que sea aleatório es muy largo lo podrías simplificar haciendo 10 mapas a mano ya sea en código o con Tile.
Habría que crear los diálogos que lo podemos hacer el jueves que viene y de música aún no tenemos nada @Zaedlen

**Comment by JuanCasado** [comment]
He estado viendo lo de la generación de niveles y está muy guay, molaría quizá que controlaras el ratio de aparición de los objetos para que por ejemplo en la parte inferior hubiera algo más de probabilidad de que aparecieran que arriba e insisto, por favor no pongas valores fijos, pon de tamaño de la pantalla (ancho y alto) los valores máximos que slick te los dice en tiempo de ejecución y haz los rectángulos de forma proporcional a dichos valores @Zaedlen

**Comment by Zaedlen** [comment]
Tranquilo, este era solo un BasicGame de prueba para poder ver el algoritmo e ir haciendo pruebas. Aun me queda hacer una serie de clases que permita al sistema ir agrupando los positivos por habitaciones y guardarlas, de forma que la colección de dichas habitaciones es lo que constituirá el mapa, es lo que se pintara y es lo que permitirá saber al personaje donde se encuentra. Por eso puse simplemente esos valores para los rectángulos.

Te pido sin embargo que cuando tengas un momento me pongas una pequeña nota de como quieres dichas proporcionalidades, es decir, dijimos por ejemplo que la altura de la habitación era de 80. Divido ahora 80 entre el stardard de altura y ese valor lo utilizo sobre el alto de pantalla para hallar esa proporción. Algo así? Mas que nada para usar los dos el mismo razonamiento y que luego no haya problemas de escalas entre los distintos elementos.

**Comment by JuanCasado** [comment]
Antes de meterme a hacer la parte gráfica de la jugabilidad del personaje voy a hacer primero lo que queda del inventario guardado de datos y la parte de mostrar estos en la tienda etc así como hacer la interface de desarrollo para que podamos ajustar cualquier parámetro para los test, si te parece bien podemos coordinarnos de la siguiente forma.

Respecto a la dimensión del personaje creo que lo mejor es que la elijas tú ya que podrás ver respecto al mapa qué tamaño es el que mejor se ajusta. Sería tomar el alto y dividirlo entre un valor que consideres proporcionado por ejemplo ALTO_DE_PANTALLA/10 y si quieres el ancho del personaje lo puede calcular usando la proporción de las imágenes para no deformarlo. Lo único porfa a izquierda y derecha deja un margen tipo ANCHO_DE_PANTALLA/7 o el que veas para las naves, el personaje debe poder disparar por las habitaciones más externas así que un flag que las identifique. Ya veo los que hayas puesto

---Viernes:
Voy haciendo eso mientras haces la parte de la generación.
--Domingo:
Integración de ambas partes en un mismo proyecto (ShutterEarth)
Métodos de comunicación etc..
---Lunes:
Hago el movimiento del personaje y la animación de las balas
Haces la música y una interface para mostrar los textos de la historia.
--Martes:
Integración de la historia dentro del juego.
Movimiento de las naves.
--Miércoles:
Batalla final contra el boss. Este día va más flojo por si hemos tenido problemas.
--Jueves:
Corrección de errores 

Vamos justos de tiempo, pero vamos bien, si ocurre cualquier problema va a haber que priorizar contenido, mejor un proyecto feo y en el que hayamos tenido que recortar ideas pero que sea jugable y tenga aspecto de terminado que algo que parezca a medias.

@Zaedlen

**Comment by JuanCasado** [comment]
La parte de infraestructura de clases, menús etc está ya hecha entera, falta lo que sería la parte dinámica y visual del juego, puedo ir haciendo cosas pero sin tener un mapa sobre el que trabajar es mucho más difícil, cuanto te quedaría hasta tener terminado el generador de niveles? 

@Zaedlen

**Comment by JuanCasado** [comment]
Creo que te estás liando mucho con lo de las salidas cuando sería más fácil ver simplemente si justo encima de la x,y del personaje hay otra habitación @Zaedlen
