### ISSUE TITLE
Fondos del edificio

### ISSUE THREAD

**Issue by UndMe** [TecnologiaVideojuegos/proyecto-videojuego-team6#13]
Chicos hoy he estado liado con el tema de los fondos y demás, que me dijisteis que os hacían falta para ver de que tamaño crear cada habitación y ya lo tenéis. 
He hecho 10, si necesitáis mas decirme y las hago, están dentro de la carpeta de ARTE>ESCENARIO.
Tenéis 3 carpetas que contienen las imágenes, el nombre de la carpeta es el tamaño en pixeles que tienen las fotos que estén dentro.
Si necesitáis que las reduzca o cualquier cosa decidme, pero las proporciones mas o menos han de ser así, ya que sino se ve muy apretado o de alto o de ancho. 

Probarlo y me contáis que tal queda, y si podéis poner alguna foto para verlo os lo agradecería.

**Comment by JuanCasado** [comment]
Los fondos están guay, creo que los de 255-300 son demasiado pequeños, entornos a 500-300 o más de largo sería lo ideal

Hay un problema con la animación de salto y es que sube pero luego no cae, si pudieras hacer otra serie de 4 imágenes para la caída estaría genial 

@UndMe

**Comment by JuanCasado** [comment]
Si pudieras hacer tres imágenes grandes porfa, una como la de la tierra que ya has subido estaría muy guay pero sin botones ni nada y en color claro para el fondo de los menús y otras que fueran simplemente el fondo para poner detrás de todo mientras se juega y otra para las batallas finales

**Comment by UndMe** [comment]
Deacuerdo, pero necesitais algun fondo mas o con los que hay son suficientes? Los he hecho de varios tamaños porque tenia de referencia la imagen que hice del boceto y ahi las habitaciones eran de distinto tamaño, pero si quereis que todas sean de 500*300 las edito y ya esta.

Respecto a la animacion del salto, voy a ver si entre hoy y mañana la tengo terminada y os la subo para que la probeis.

Las imagenes de los fondos tratare tambien de hacerlos, tengo hecho ya practicamente el diseño de la pantalla de inicio, ese creo que de esta tarde no pasa que os lo suba, para que lo pongais ya y ver si queda bien de tamaño y demas.

@JuanCasado

**Comment by UndMe** [comment]
Vale perfecto @JuanCasado mientras tanto voy haciendo lo que falta y me decis si os parece bien o si hay que modificar algo.
Lo que si necesito saber es la cantidad de fondos que hay que hacer de habitaciones para ponerme ha dibujar mas o no, espero que me diga @Zaedlen
