### ISSUE TITLE
DESAPARECIDOS

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#14]
Suponemos que @pablopg99 no va a venir ni ha hacer nada, si de verdad quiere participar que se manifieste.

@daniel-diazl No has subido nada del proyecto y se suponía que ibas a hacer las imágenes del personaje, sube algo o di algo XD

**Comment by Zaedlen** [comment]
No estoy muy seguro y pido a @UndMe que se manifieste, pero creo que era justamente al revés, que @pablopg99 era el de las imagenes del personaje. Que @UndMe nos lo confirme no vaya a ser que el pobre Pablo sea declarado desaparecido sin motivo xD

**Comment by UndMe** [comment]
Efectivamente, la imagen o imagenes mejor dicho del personaje era @pablopg99 quien las iva a hacer. El otro dia le pregunte y me dijo que todavia no las tenia, a ver si puede leer estos mensajes y decirnos algo al respecto.

**Comment by pablopg99** [comment]
Lo primero de todo, perdonad por la ausencia y el no haber respondido a esto antes, pero es que tampoco me notifica de ninguna manera
Ya he subido la primera imagen del personaje, darme opiniones y eso. Si os mola y tal intentare tener la animación de correr para mañana.
@JuanCasado @Zaedlen @UndMe

**Comment by JuanCasado** [comment]
Está muy guay, tendrías que hacer las animaciones de correr hacia ambos lados, saltar (y caer) hacia ambos lados y eso mismo con cada arma, por ahora tenemos pensado 5 armas en total
@pablopg99

**Comment by pablopg99** [comment]
No se que armas queréis introducir pero había encontrado dos imágenes con algunas ya hechas que nos podrían venir bien, los acabo de subir.

@JuanCasado
