### ISSUE TITLE
Imágenes de personajes

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#15]
Por ahora tenemos los dos enemigos básicos, el fuerte y el normal hechos, quedaría:

- Malo final (el que raptó a nuestra hija) del que hacen falta los scripts de movimiento y algún dibujo un poco más en grande si diera tiempo para poner en los diálogos, se podría aprovechar el script también.

- Nosotros el personaje principal que más de los mismo, scripts y alguna foto

- Boss1 

- Boss2

Para los bosses se me había ocurrido poner naves espaciales que son fáciles de animar si se mueven por fuera del edificio, una que sea grande y dispare solo en una planta y otra más grande que podría no verse entera y que dispare en dos o tres a la vez

**Comment by UndMe** [comment]
Sisi las naves es buena idea, dehecho era lo proximo con lo que iva a ponerme.
Cuando las tenga hechas las subire como el resto de cosas @JuanCasado
