### ISSUE TITLE
Música

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#16]
No hemos hablado nada de este tema pero deberíamos de incorporar algo que suene de fondo, se que hay repositorios con efectos de sonido y poco más, pongan ideas :)

**Comment by UndMe** [comment]
@JuanCasado como esta mañana hemos hablado, he subido una carpeta de MUSICA que acabo de grabar con un teclado que tengo y me parece que podria estar bien para ponerla. Ya esta editada y todo quitado ruido de fondo y demas, La cancion de fondo la idea es repetirla hasta que el nivel se pase, se puede poner mas rapido incluso por si queremos que segun se avance de nivel suene mas rapido.

Mirarlo y me comentais.

**Comment by JuanCasado** [comment]
Los que has subido están bien, habría que recortarlos y eso pero se pueden usar, quedaría uno para dentro del juego y otro para cuando sea la batalla final

**Comment by JuanCasado** [comment]
He metido ya la música al juego @UndMe

**Comment by UndMe** [comment]
No consigo hacerlo sonar, hay que activar alguna opcion o deberia de salir automaticamente cuando arranca el juego ??

**Comment by JuanCasado** [comment]
No hay que hacer nada, lo abres y suena, comprueba que estés abriendo la última versión

**Comment by UndMe** [comment]
Y es el shutterEarth o el de drive my crazy? porque estoy probando con los dos pero nada, incluso el que tiene la opcion de registro hay veces que no me deja escribir nose porque .....

**Comment by JuanCasado** [comment]
Es el de ShutterEarth.
No deja escribir porque como maneja slick los text input, le he puesto para que dándole al tabulador fuerce la entrada de texto, si le das te dejará.

**Comment by JuanCasado** [comment]
Comprueba que este sea el init de tu clase Game, si no lo es es que tienes una versión antigua o algo

![image](https://user-images.githubusercontent.com/37184487/39898677-1b740ec0-54b8-11e8-8013-de980f268024.png)

**Comment by UndMe** [comment]
![imagen](https://user-images.githubusercontent.com/37188090/39898839-eabf61de-54b8-11e8-9bef-85b66e0a2da6.png)

Asi tal cual lo tengo y cuando lo ejecuto no suena ... que cosa mas rara, ati en mac te suena sin problema ??

**Comment by UndMe** [comment]
Acabo de bajar la ultima version que ya pone loop() pero aun asi no se escucha... pensaba que era porque tenia los cascos puestos pero no, porque con los altavoces del portatil tampoco suena, dehecho estoy con musica asique tendria que escucharse.
En la pantalla de login deberia de sonar ?

Por cierto creo que voy a hacer ahora los textos para que los pongas ya :D

**Comment by JuanCasado** [comment]
Si osea, es de hecho la primera instrucción en ejecutarse nada más se inicia el juego jajajajaja, debería sonar en todos lados

Puede que sea algo concreto de tu ordena, a ver si al resto les pasa :/

**Comment by JuanCasado** [comment]
@Zaedlen Puedes confirmar si se escucha o no el juego????

**Comment by UndMe** [comment]
Vale si, que pruebe alguien mas y asi salimos de la duda.
Estoy haciendo los carteles para los menus y asi por lo menos sabemos donde clickamos xD.

**Comment by JuanCasado** [comment]
He buscado ya unos cuantos archivos de sonido y creo que ya tenemos de sobra así que no harían falta más, centrarnos en las imágenes y el código

**Comment by JuanCasado** [comment]
He cambiado el formato de la música de ogg que a pesar de ser un forma libre parece no ser del todo compatible con windows a wav que es propiedad de microsoft, no obstante parece que en windows parece no escucharse, a espera de una solución mejor resulta que los ejemplos del propios slick no se escuchan en windos así que probablemente el problema sea vuestro.

@UndMe @pablopg99 @Zaedlen

**Comment by UndMe** [comment]
Es raro, porque me meto a la carpeta de media donde estan todas las canciones e imagenes y con el mismo reproductor de windows puedo escucharlas sin problemas, y las .ogg con el VLC, pero sin embargo cuando entro al juego nada de nada.. nose porque ...

**Comment by JuanCasado** [comment]
Ni idea, yo lo he estado hablando con los otros grupos y a todos los va bien y las llamadas que hacen a la música son las mismas que hago yo, en cualquier caso yo si lo escucho jajajajjja

**Comment by UndMe** [comment]
Voy a probarlo ahora en mac a ver si es eso el problema, por lo menos para salir de la duda y con lo que sea te digo por aqui.
