### ISSUE TITLE
Pantalla de INICIO

### ISSUE THREAD

**Issue by UndMe** [TecnologiaVideojuegos/proyecto-videojuego-team6#17]
Chicos acabo de subir hace nada, una nueva carpeta a la parte de Arte > Concept Art > INICIO.
Mirar el archivo que se llama INICIO.png o el .jpg, es el mismo. He pensado en poner esa pantalla nada mas entrar al juego, a quedado bastante chulo pintado y demas.

El tamaño que tiene la imagen es de 1280*901, si necesitais que la reduzca decirme.

Darme vuestras opiniones. @JuanCasado @Zaedlen @pablopg99

**Comment by JuanCasado** [comment]
Por ahora está quedando así, habría que hacer los textos para los botones y eso

![image](https://user-images.githubusercontent.com/37184487/39494545-19f827de-4d97-11e8-8f60-69cdf5188b89.png)
![image](https://user-images.githubusercontent.com/37184487/39494561-2a44b88c-4d97-11e8-823c-2a6091145c59.png)

Esta sería como quedaría la tienda y queda un poco raro con ese fondo, a parte de los dos fondos de juego (el normal y el de la batalla final) puede que quedara guay hacer otro más para la tienda y el menú de estadíasticas
![image](https://user-images.githubusercontent.com/37184487/39494732-db25de2e-4d97-11e8-821b-d9b3cfafbb02.png)

**Comment by JuanCasado** [comment]
Por cierto, el fondo mola mazo jajajaj :P @UndMe

**Comment by UndMe** [comment]
Acabo de subir ahora mismo un par de fondos de los que me pediste @JuanCasado para el videojuego.
Esta dentro de la carpeta CONCEPT ART > ESCENARIO, se llaman escenario corregido de dia y de noche, pueden quedar bastante bien de fondo y he hecho dos por cambiar un poco, que unas veces aparezca el nivel de dia y otro de noche, hechale un vistazo y dime que te parece.

**Comment by JuanCasado** [comment]
WoW, molan mazo, esos pueden ser los fondos que se vean detrás del edificio mientras se juega, el de día que sea el normal y que cuando la cosa se ponga chunga rollo batalla boss se haga de noche.

Quedaría algo para poner de fondo en la tienda y en el menú de estadísticas, la disposición de los objetos para la tienda sería la de la foto de arriba, un botón para salir a la izquierda, una foto de lo que se va a aupgradear en el centro, botones para cambiar entre items a los lados y abajo rectángulos que indiquen el nivel del objeto 

Muy buen trabajo @UndMe
