### ISSUE TITLE
IMAGENES PERSONAJES Y ARMAS

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#18]
Las imágenes que has subido de las imágenes están bien, sería aplicárselas al personaje del héroe osea la madre y poco más, sería de esas elegir cinco, el rol de cada arma por como lo estoy programando sería:

- Arma mínima (daño bajo,  velocidad de disparo normal, gasta pocas balas) --> Pistola pequeña
- Arma base (daño normal, velocidad de disparo normal, gasto de balas normal) --> Pistola grande
- Arma fuerte (daño alto, velocidad de disparo lenta, gasto de balas alto) --> Escopeta
- Arma rápida (daño normal, velocidad de disparo rápido, gasto de balas alto) --> Ametralladora 
- Arma definitiva (daño muy alto, velocidad de disparo normal, gasto de balas muy alto) --> Arma Alien (Es la única que puede no encajar con las que ya has hecho y que puede que haya que hacer de nuevo)

**Comment by JuanCasado** [comment]
Adicionalmente habría que hacer una imagen que fuera como una pequeña explosión o fogonazo que tenga el tamaño del héroe pero en transparente y que coincida aproximadamente con el cañón de todas las armas, la idea es colocarlo desde el código encima del personaje de forma que parezca que dispara esté en el estado de animación que esté @pablopg99

**Comment by JuanCasado** [comment]
Hey, puedes confirmar si vas a hacer la parte de las armas, el personaje y el malo, no viniste el jueves pasado y por lo general has estado poco activo @pablopg99 

Porfa @UndMe pregúntale por whats o algo, si no va a hacerlo nos va a tocar a nosotros...

**Comment by JuanCasado** [comment]
Necesitamos:
- Movimiento hacia la derecha (4 min)
- Movimiento hacia la izquierda (4 min)
- Salto hacia la derecha (3 para la subida y 2 para la bajada)
- Salto hacia la derecha (3 para la subida y 2 para la bajada)
Esto habría que hacerlo para el personaje principal con cada arma, en total 5 armas:
- Pistola debil
- Pistola fuerte
- Escopeta
- Ametralladora
- Cañón alien

Adicionalmente habría que diseñar al malo lo cual consistiría en hacerle las animaciones de movimiento derecha e izquierda y salto derecha e izquierda, el malo solo tendrá un arma y aquí es ya como te lo imagines tú

@pablopg99

**Comment by pablopg99** [comment]
Ya tengo todas las imagenes del personaje con el arma 1. Pero he intentado hacer una carpeta para subir todas las imagenes ordenadas y la he liado un poco. Puedes crearme una carpeta llamada Personaje Arma 1, para poder subir ahi las imagenes de una forma mas ordenada?
@JuanCasado

**Comment by JuanCasado** [comment]
Ya está hecho :P @pablopg99

**Comment by pablopg99** [comment]
No se que tal quedara al poner la misma imagen para iniciar el salto y aterrizar, tampoco sabia como hacerlos distintos sinceramente. La imagen de "aire" sera la misma para todo momento en que el personaje no esté tocando el suelo y la de parado sera la transición entre saltar y correr.
Si puedes montarlo para ver si algo queda raro y hay que corregirlo.
@JuanCasado

**Comment by JuanCasado** [comment]
No te preocupes, monto todo en un rato, vete si eso haciendo las 5 fotos de las armas o las fotos del sprite del malo <3

**Comment by pablopg99** [comment]
Te acabo de subir las imagenes con el arma 2 en la misma carpeta

**Comment by JuanCasado** [comment]
Puedes subir de las armas que vayamos a usar una foto del arma sola para que aparezca seleccionarla en el inventario @pablopg99

**Comment by JuanCasado** [comment]
Sep, pero la foto esa lo último que no corre tanta prisa <3 @pablopg99

**Comment by JuanCasado** [comment]
Están muy guay las fotos, esta noche hago los sprites y los meto, quedaría el malo y fotos de las armas solas sobre fondo transparente, todo lo que sean fotos de nuevos tipos de bala son bienvenidos :)

@pablopg99 @UndMe

**Comment by JuanCasado** [comment]
No me salen, tienes que haces un push o algo @pablopg99

**Comment by pablopg99** [comment]
Estas subidas directamente en la carpeta que tu me creaste, sino cuando llegue a casa las subo a otro lado

**Comment by JuanCasado** [comment]
No no, no te preocupes, ya me dejó, las estoy recortando @pablopg99

**Comment by pablopg99** [comment]
Algún arma en especial para el malo? estaba pensando en un rifle de francotirador o algo parecido 

@JuanCasado

**Comment by JuanCasado** [comment]
El malo lo estás dibujando tú @pablopg99  o @UndMe ?

**Comment by JuanCasado** [comment]
En cualquier caso el malo es como el jefe alien así que algo que sea así un poco futurista mejor @pablopg99

**Comment by pablopg99** [comment]
La cosa es que ni yo he hecho un alien ni @UndMe ha hecho un personaje. Yo si quieres puedo usar la misma base del personaje que ya tengo para hacer otro humano con una capucha, una capa y una máscara que use un rifle o algo.

**Comment by JuanCasado** [comment]
Vale, lo veo bien @pablopg99

**Comment by JuanCasado** [comment]
Si lo haces por ejemplo en negro y azul podemos cambiarle el color al proyectil de las naves y que dispare eso y ya quedarían hechos todos los gráficos @pablopg99

**Comment by JuanCasado** [comment]
Está to bien, si tienes las fotos hoy las monto y las meto, si la generación del mapa la terminamos hoy tb todavía podemos llegar al jueves 

@pablopg99 @UndMe @Zaedlen
