### ISSUE TITLE
ENEMIGO NAVE

### ISSUE THREAD

**Issue by UndMe** [TecnologiaVideojuegos/proyecto-videojuego-team6#19]
Buenas noches !

He subido una carpeta que se llama enemigo nave dentro de arte/conceptart que tiene un par de imágenes (una con fondo y otra sin fondo) para el enemigo final y la nave. Esta podría ser reutilizada para la tienda o algún menú secundario. 

Echadle un ojo a ver que opináis y me decís por aquí.

**Comment by JuanCasado** [comment]
La nave está perfecta y sí, se podría hacer una pequeña animación que saliera volando por los menús de vez en cuando y podría estar guay además de ser original, quedaría muy bien.

Faltaría la otra nave y se me está ocurriendo que ya que la mayoría de imágenes las tienes con y sin color podemos hacer los scripst en blanco y negro rollo una imagen fondo blanco borde negro y la siguiente fondo negro borde blanco como parpadeando para cuando se reciba daño
@UndMe

**Comment by JuanCasado** [comment]
La animación de la nave está ya hecha, dejo puesta una demo que la podáis ver, habría que hacer la otra nave y su animación podría adaptarse a esta, pero disparando 3 proyectiles en vez de uno solo.

@UndMe @Zaedlen @pablopg99

**Comment by UndMe** [comment]
Acabo de subir ahora mismo la nave que faltaba @JuanCasado, esta dentro de la carpeta de ENEMIGO NAVE, se llama ENEMIGO NAVE FINAL. Cuentame que te parece y si te vale :D
