### ISSUE TITLE
Introducción a Tiled Map Editor

### ISSUE THREAD

**Issue by UndMe** [TecnologiaVideojuegos/proyecto-videojuego-team6#2]
Os dejo una pagina web que he encontrado para manejar Tiled bastante interesante. 

http://seryusjj.github.io/capitulosTiledmap/capitulo1.html
--------------------------------------

***Paginas web para assets: ***

http://kenney.nl/assets
https://opengameart.org/

**Comment by JuanCasado** [comment]
Por ahora he empezado ha hacer el HUD de un juego básico, lo que viene a ser vidas, mostrar el arma equipada y las balas que tiene, si pudieras ir haciendo/buscando alguna imagen sobre eso estaría guay porque debido a la temática elegida son cosas que vamos a utilizas si o si.

Si haces algún mapa de Tiles más súbelo tb porfa
