### ISSUE TITLE
PRESENTACION

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#20]
El próximo jueves tenemos examen y no creo que podamos ir a la presentación, solo podríamos estar los primero 45 min de teoría. Supongo que los que si podréis ir sois los de primero que os habéis centrado más en las imágenes.
No creo que la presentación dure demasiado así que lo mismo con lo que habéis ido haciendo podéis llenar todo el espacio, pero si queréis mostrar un ejemplo del programa funcionando le podéis mostrar el [Versión jugable.](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team6/tree/master/Programacion/Pruebas/AliensDriveMeCrazy) al que le he metido todas las imágenes que habéis pasado con las animaciones que tenemos y todo, tendríais que decir que bueno, faltan los boses, la generación del edificio y la integración de la historia en el juego...

Si tenéis problemas para ejecutarlo o alguna cosa decirlo, hay que tener bastante resolución en la pantalla como para verlo bien, la versión definitiva será escalable a todas las pantallas.

@Zaedlen @UndMe @daniel-diazl @pablopg99

**Comment by UndMe** [comment]
@JuanCasado perdona por responder un poco tarde, pero ayer estaba liado con un examen que he tenido hoy y me ha resultado imposible entrar.
El jueves pasado no pude estar en la clase por lo que no vi lo que pidio tener hecho para este jueves, aunque me imagino que dijo de hacer un presentacion como comentas no ?

Decirme porfavor un poco por encima si pidio algun requisito en especial mas que nada para tenerlo presente y si dijo de hacer la presentacion en alguna plataforma en especial o algo.

**Comment by JuanCasado** [comment]
Es nada más hablar sobre el videojuego durante 5 min cómo dijo a principio de curso para que todos vean las ideas de todos, por suerte no cuenta para nota jajajja

@UndMe 

![image](https://user-images.githubusercontent.com/37184487/39712731-6104f6b6-5224-11e8-914e-b4d9d55deea7.png)

**Comment by UndMe** [comment]
Vale perfecto, no os preocupeis @JuanCasado que sino estais ya la hacemos nosotros.
Intentare alomejor llevar una presentacion aunque sea pequeña de las cosas que vamos a poner y demas y luego pongo la demo que esta hecha del juego para que se hagan una idea. 
No os preocupeis 👍
