### ISSUE TITLE
TEXTOS

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#21]
Los textos que nos hacen falta son: 

- EXIT
- BACK
- USER:
- PASSWORD:
- LOG IN
- NEW
- PLAY
- STORE
- UPGRADE
- <-
- ->

Los dos últimos son flechas XD

@UndMe

**Comment by JuanCasado** [comment]
Había pensado en dejar los fondos amarillos y solo poner el texto con fondo transparente encima.
Déjales un poco de margen a estas imágenes, pero el mismo por todos lados, rollo un 50 % de la imagen de margen a cada lado @UndMe

**Comment by JuanCasado** [comment]
ups 5%

**Comment by UndMe** [comment]
Uf, he visto tarde este mensaje @JuanCasado, acabo de subir una serie de textos.
El fondo esta en rojo porque tenia pensado mantener los que puse en la pantalla de inicio y demas, miralos y sino les cambio el color.

Aun asi me falta alguno de los que has puesto, voy a ello cuando me digas si mantengo el rojo o no.

**Comment by JuanCasado** [comment]
No me convencen mucho y quedan un poco raro, si quieres los textos los hago yo que se tarda poco :P

**Comment by UndMe** [comment]
Pero estoy pensando una cosa, subi una foto del inicio que tenia ya los botones de la tienda, y de jugar y demas entonces, porque no utilizamos esa y le añado yo lo que falta de botones, y hacemos otra con el mismo fondo pero solamente para usuario y contraseña ?? 
Lo digo porque alomejor no la habeis visto y creo que esta chula.

![imagen](https://user-images.githubusercontent.com/37188090/39913448-2fc36160-5502-11e8-9ee3-91be8971d2a9.png)

**Comment by JuanCasado** [comment]
No sé, lo veo más lío, tenga ya la mitad hecho, subo el botón de log in que lo veas dentro del juego

**Comment by JuanCasado** [comment]
Ya están los botones puestos @UndMe

**Comment by UndMe** [comment]
Perfecto @JuanCasado voy a hecharle un vistazo y te comento que tal :D

**Comment by JuanCasado** [comment]
Justo ahora estrían todas las animaciones e interfaces, solo quedaría lo que es el juego en si, pero para ponerme con eso necesito que esté la generación de mapa hecha.

Opiniones please: @UndMe @Zaedlen @pablopg99

**Comment by UndMe** [comment]
Porfavor revisar el tema del sonido para saber si soy yo al unico que no le suena o es algo generalizado.
Por cierto @JuanCasado el LOADING que has puesto al entrar al juego me gusta bastante :D
