### ISSUE TITLE
DISPARO

### ISSUE THREAD

**Issue by UndMe** [TecnologiaVideojuegos/proyecto-videojuego-team6#24]
Aquí os dejo la imagen del disparo a izquierdas y a derechas que disparan los bichos.
Mirad a ver si os gusta para que lo dispare también la nave o que.
Podeis encontrarlas en la carpeta de ENEMIGO BASE.

**Comment by JuanCasado** [comment]
Le meto ahora las balas, creo que quedan mejor solo en los aliens pequeños, si quieres hacer una distinta para las naves estaría muy guay, por cierto la nave grande ya está en el juego @UndMe

**Comment by UndMe** [comment]
A quedado bastante bien yo creo no ??? A ver cuando tenemos el edificio que quiero ver a los bichejos disparando la lava verde :D

**Comment by JuanCasado** [comment]
Lo de las naves estaría muy guay, aunque fuera una peloteja rollo bola de energía, en cualquier caso urge un poco más lo del malo final, a pablo le quedan todavía 3 veces más el sprite del héroe y las fotos de las armas, si haces lo del malo creo que iremos mejor de tiempo @UndMe 

Hago ahora una simulación rápida para poner la lava verde

**Comment by pablopg99** [comment]
Chicos, para el disparo del arma alien que he diseñado tendríamos que usar una especie de disparo láser azul o algo parecido.(Podeis encontrar el arma a nombre de arma 5 dentro de la carpeta PERSONAJES_ARMA_1)
@UndMe @JuanCasado  @Zaedlen

**Comment by UndMe** [comment]
Chicos acabo de subir ahora mismo la imagen del disparo de la nave final. Esta dentro de ENEMIGO BASE > DISPARO BOLA NAVE RECORTADA. 

Decirme que os parece. 
@JuanCasado @pablopg99 @Zaedlen

**Comment by JuanCasado** [comment]
Ya está integrada la nueva bala así como las nuevas imágenes del personaje, faltan las del arma 5

@UndMe @pablopg99 @Zaedlen

**Comment by UndMe** [comment]
Voy a mirar como a quedado :D
