### ISSUE TITLE
APLAZAMIENTO

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#25]
Estamos en el límite de poder llegar al jueves con todo hecho, quedan las imágenes de las armas que es algo relativamente ligero, las imágenes del malo e integrar la historia con el juego.
@UndMe @pablopg99 
Hasta el momento solo ha habido problemas de compatibilidad debido a windows y debido a los distintos tipos de pantalla que intento arreglar.

El mayor problema que tenemos ahora viene de la generación aleatoria de los mapas, @Zaedlen ha entregado su parte muy tarde, necesita de integrarse con todo el resto del juego y además debe de reescalarse al resto de medidas y debido a que no habla no puedo saber si va a tardar mucho o no.

Lo que si que está cerca es la entrega y desde mi punto de vista hay dos opciones, prescindir del mapa aleatorio y poner los personajes sobre un fondo y mapa plano como he tendido durante las pruebas o entregar el proyecto el 21 de junio, me ha dicho el profesor que no habría problemas, haríamos el examen y simplemente entregaríamos el juego más tarde.

**Pido por favor votad si o no al aplazamiento antes de mañana a las 6:00 para poderlo notificar al profesor**

**Comment by pablopg99** [comment]
Yo creo que deberíamos de aplazarlo, no solo por añadir lo de la generación de mapas sino para tener unos días de prueba para comprobar que todo funciona bien.

**Comment by UndMe** [comment]
@JuanCasado perdonar que ayer no vi esto. Por mi no habria problema a la hora de aplazarlo, si nos vemos muy apurados es mejor hacerlo bien y entregarlo un poco mas tarde, que intentar hacer una chapuza y quede mal.

Conmigo podeis contar.
