### ISSUE TITLE
MEMORIAS

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#26]
En la carpeta de Documentacion/Memorias/ podéis ir añadiendo los documentos que hagáis, no tienen que ser demasiado largos supongo, digamos máximo 5 páginas, podéis incluir fotos y hablar de las herramientas que habéis usado, estaría guay una captura mientras editáis una foto por ejemplo o lo que se os ocurra 

@Zaedlen @pablopg99 @UndMe

**Comment by UndMe** [comment]
Perfecto @JuanCasado voy a hacerla a lo largo de la mañana y cuando la tenga la subo.

**Comment by JuanCasado** [comment]
Ya está el documento de la memoria, que cada uno suba su parte y las junto @pablopg99  @Zaedlen , ya he metido la de @UndMe

**Comment by UndMe** [comment]
@JuanCasado estoy cambiando unas cosas, cuando termine la subo cambiada y te aviso.

**Comment by pablopg99** [comment]
Acabo de subir la mia @JuanCasado

**Comment by JuanCasado** [comment]
Ya he metido todo lo que habéis subido en la memoria común
@pablopg99 @UndMe 
solo queda @Zaedlen

**Comment by UndMe** [comment]
He tenido que editar unos textos que nose porque se habran copiado mal, en la parte de la memoria que yo he realizado.

**Comment by Zaedlen** [comment]
Ya está mi parte añadida. He puesto también un índice

**Comment by Zaedlen** [comment]
IMPORTANTE
Revisad cada uno su parte en el documento común por aquello de las faltas, palabras escritas a la mitad y otras erratas. No tardáis nada.
Y deberíamos añadir un anexo final con las referencias a todos los contenidos que hayamos utilizado de terceros de los que recordemos el origen. El canal de Youtube al que se hace referencia, webs de donde se sacaron sprites e imágenes y esas cosas.

**Comment by JuanCasado** [comment]
Perfecto, la paso a pdf y la meto en la wiki
