### ISSUE TITLE
Tema/Historia

### ISSUE THREAD

**Issue by Zaedlen** [TecnologiaVideojuegos/proyecto-videojuego-team6#3]
Al final quedamos en hacer un plataformas con, de momento:

- Salto

- Disparo

La temática y/o historia no había quedado muy clara, más allá de que tiene que haber armas de fuego. He estado pensando y creo que podríamos hacer algo tipo CSI, series de detectives o policías americanas, todo en tono de humor: Algunos tacos aquí o allá, muchos topicazos, fantasmadas y obviedades. Tipo pues eso una mezcla de CSI, Hora punta, Arma letal... Algo así

Puedo hacer una minihistoria que suponga la excusa para avanzar por los niveles a tiro limpio: resolver un caso, rescatar a alguien, algo así

Y además nos daría una pista para empezar a trabajar en mecanicas, escenarios, npc´s y el personaje principal

No se, id poniendo argumentos a favor o en contra aquí o también nuevas tematicas

**Comment by JuanCasado** [comment]
Me parece una temática genial que engloba muy bien lo que estuvimos hablando en el último lab, por ahora durante las vacaciones podemos ir trabajando un poco por separado con la idea de fomentar algo más la creatividad y el desarrollo personal de la idea.

En el siguiente lab realizaremos el documento de diseño del videojuego así que documentar y subir a vuestros respectivos branches todas las pruebas que hagaís tanto con slik2d como con tiled.

Siguiendo la temática de un plataformas con disparos yo voy a intentar empezar a hacer hacer algo similar a lo siguiente:

![image](https://user-images.githubusercontent.com/37184487/37874427-39c69a44-302f-11e8-89e5-4731a7c5d72a.png)

**Comment by JuanCasado** [comment]
WoW, mola mazo la historia que has hecho, está súper súper currada!!!!! @Zaedlen 

Tenemos historia tenemos más o menos la idea de como queremos que sea el juego, nos faltan algunos bocetos e imágenes y por ahora vemos progresando bastante bien

**Comment by Zaedlen** [comment]
Gracias! Ligeramente basada en la invasión francesa ;)

He añadido uno dos párrafos mas presentando a la que podría ser la protagonista. De nosotros depende presentarla o desvelar su pasado antes o después durante el juego. Y he pasado todo el texto a un .md para facilitar su lectura sin tener que descargarlo.

Voy a ver si termino los diseños, sobre todo de armas.
