### ISSUE TITLE
Necesitamos imágenes

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#4]
La parte básica del movimiento del personaje, disparos etc está ya terminada así como el esqueleto de la organización de las clases para portar armas u otros objetos.
Estaría bien comenzar a hacer las imágenes de juego, sobre todo las de los personajes, animaciones para caminar, balas, armas... Necesitamos esto no solo para comenzar a introducirlo en el juego si no para poder incluirlo en el documento de diseño que tenemos que entregar ya dentro de nada.
A nivel de código queda implementar la IA de los NPCs y decidir algunas de las mecánicas a seguir por nuestro personaje.

**Comment by Zaedlen** [comment]
Lo he comentado ya en el otro mensaje, pero bueno. Quiero subir algunos diseños de armas. Tan pronto como termine el examen del martes les doy los últimos retoques y las subo. Lo estoy haciendo a nivel de concept art, si no queremos que sea tan detallado en el juego supongo que luego habría que hacer de ellas los pixel art si las aprobamos.

En cuanto a los personajes, lo mismo, aunque más a nivel de dar ideas. No se cual será el resultado final pero me resulta más difícil dibujar personas que armas, objetos o paisajes.

Por ultimo, y en referencia a esos fondos y mobiliario de niveles, así como (es una sugerencia) algunas láminas para pantallas de carga o partes de historia donde puede salir un texto, convendría hablarlo y ponerse de acuerdo sin cambios en el estilo, temática, etc antes de ponernos a dibujar y diseñar como locos.

**Comment by Zaedlen** [comment]
He subido a mi branch cómo llevo hasta ahora la pistola láser. Intento basarme en armas reales y tratar de modificarlas, que es un poco lo que habría pasado en ese mundo.

![boceto_pistola](https://user-images.githubusercontent.com/34587930/38284231-7c7e1230-37ba-11e8-8bd9-e288156d1aec.jpeg)

**Comment by Zaedlen** [comment]
Bueno, al final me ha dado tiempo a estás dos armas. Me quedan pendientes algunas ideas para personajes y discutir mañana en el lab los escenarios y la estética mientras hacemos el docu.

![fusilmicroondas](https://user-images.githubusercontent.com/34587930/38341708-3db518d0-387a-11e8-8bb7-33c9d461d7e0.jpeg)
![pistolalaser](https://user-images.githubusercontent.com/34587930/38341709-3dd00ea6-387a-11e8-859b-496a70e6a12b.jpeg)

**Comment by JuanCasado** [comment]
Podéis hacer imágenes PNG fondo transparente de los siguientes textos con una tipografía guay (que quede bien sobre fondo amarillo (el color))

- SALIR
- Registrarse
- Entrar
- ATRÁS
- Tienda
- Jugar
- OnLine
- Estadísticas

El tamaño sería aproximadamente de 100 px de alto máximo

PD Si os mola como queda podemos hacer más partes de texto con este método

**Comment by UndMe** [comment]
Deacuerdo, hoy me ha sido imposible hacer nada porque no he podido. Intentare ponerme a hacer algun cartel de los que dices para llevarlo mañana, a ver si consigo hacer alguno decente.
@JuanCasado

**Comment by JuanCasado** [comment]
Yo mañana tengo examen de inglés y no voy a poder ir a clase, pero con las imágenes os tenéis que poner las pilas ya, quedan los fondos por hacer, al menos uno para los menús y otro para el background del juego, los de las habitaciones y toooodas las fotos de los personajes etc, vamos bastante justos de tiempo en ese sentido

**Comment by UndMe** [comment]
Lose lose, pero tampoco es algo facil que se pueda hacer en un dia, y muchas de las cosas tampoco veo que queden bien y directamente prefiero no subirlas. Aun asi ahora tengo el puente y creo que puedo recuperar algo de tiempo porque esta semana pasada entre entregas y examenes a sido mortal el poder hacer algo ... T_T

**Comment by JuanCasado** [comment]
Una cosa importante, para estos sprites has puesto altura 320, ancho 281 y espacio 0, en todos hazlo igual para que el trabajo se a más cómodo y no haya que ir mirando como debe tratarse cada sprite

**Comment by UndMe** [comment]
Vale @JuanCasado lo tendre en cuenta, acabo de subir ahora mismo el boss base saltando, pero he tenido que cambiar esos parametros porque sino no se apreciaba muy bien. Puedo hacerlo denuevo manteniendo los que ya tenia, pero sino os dejo los nuevos para que probeis y me digais como se ve.

ancho: 250px
altura: 450 px

Aun asi los anteriores tenian de ancho 300, no 281 ...

**Comment by JuanCasado** [comment]
Pon las dimensiones que sean pero todas el mismo porfa, cambia las otras o la de la última pero todas la misma please @UndMe

**Comment by UndMe** [comment]
Vale ya esta subida la correccion del enemigo de esta tarde, al final mantengo el tamaño que tenia el primero @JuanCasado 

ancho: 300
alto: 320

Probarlo porfavor y decirme si os vale como salto. Si podeis subir alguna animacion para ver como va os lo agradeceria 😀
