### ISSUE TITLE
Movimientos del personaje y disparo terminado

### ISSUE THREAD

**Issue by JuanCasado** [TecnologiaVideojuegos/proyecto-videojuego-team6#5]
Como podéis ver en el último commit a mi branch está terminada la lógica del movimiento del personaje y de disparar, falta mucho trabajo pero los siguientes pasos deberían de ir en la línea de crear los mapas y las imágenes de los personajes, animaciones... 

Cuando nos reunamos vemos lo que habéis avanzado los demás porque a git creo que no lo habéis subido, no se si habrá algún problema y vamos uniendo lo que haya.

**Comment by Zaedlen** [comment]
A ver, ya que al final os habéis empeñado en que sea de aliens estoy arreglando una pequeña historia y pasándola a limpio. Algo pequeño con lo que poder dar un inicio y una escusa al juego.
también estoy con diseños de armas y a ver si me sale bien alguno para los personajes, todo para los concept arts; he tenido que rescatar antiguos apuntes de dibujo.

Solo pido que dejes algo para los demás y no vayas tan deprisa XD o al menos que hagamos reparto de tareas, no que de repente tengas ya medio código de juego hecho. Lo dicho, está bien pero bueno, eso, los demás también tenemos ilusión por contribuir al videojuego :)

**Comment by JuanCasado** [comment]
No tiene por qué ser de Aliens, la temática está totalmente abierta a lo que se os ocurra y decidamos el jueves que viene, el nombre de la carpeta ese simplemente por que es el del juego en el que me he basado para hacer las dinámicas, nada más.

En cuanto al código quedan infinidad de cosas por hacer y tampoco tenemos por qué partir de lo que yo haya hecho, solo es un pequeño ejemplo de lo que se podría hacer y lo he ido subiendo a GIT para que vierais algunos patrones óptimos de diseño ya que con la programación parecíais más perdidos.
