### ISSUE TITLE
IMPORTANTE - Nombre del juego y documento de diseño

### ISSUE THREAD

**Issue by Zaedlen** [TecnologiaVideojuegos/proyecto-videojuego-team6#9]
## 1 Documento de diseño
El otro día en clase dije de pasar yo a limpio el docu, indexarlo y tal. Pero para ello necesito tiempo por si hay que modificar o arreglar alguna cosa, nos damos cuenta de que falta algo o cualquier eventualidad.

Este jueves hay que entregarlo y este jueves tenemos examen de programación avanzada los de 2o. Digo todo esto porque aun no he visto que hayais subido el documento en sucio: ni foto ni la versión digitalizada y, evidentemente, no pienso ponerme el miércoles a las 23:00 a hacerlo teniendo examen al dia siguiente. AVISADOS ESTAIS

## 2 Nombre del juego
En cuanto al nombre del juego, simplemente comentar que lo he pensado y no tiene mucho sentido XD
Debido a que shutter significa cerrado, tendría más sentido ShutterEarth o CastawayAliens.

Decidme tambien algo sobre esto :)

**Comment by JuanCasado** [comment]
# Nombre
Lo de ShutterEath puede estar guay pensando en lo que pone en la historia de:
_Ahora los aliens están atrapados aquí y solo es cuestión de tiempo que uno de los dos bandos se declare vencedor. Actualmente nos encontramos en el año 2056 y la guerra continúa._
Además encaja con la idea de que estamos _encerrados_ en una casa/nivel del que no podemos salir/pasar hasta haberlo superado.
# Documento
En cuanto tengaís los documentos pasados subidlos y si os da tiempo a las fotos de background y del personaje en png fondo transparente también y lo edito para hacer ejemplos de posibles escenas del juego, en cualquier caso notificarlo con una issue eque nos llegue una notificación.
# Extra
A modo conceptual deberíamos incluir un diagrama de casos de uso del juego, lo hago en ahora esta tarde y lo subo a la carpeta de diseño

**Comment by JuanCasado** [comment]
Ya está subido en la carpeta Documentacion/Diseño_y_mecánicas el diagrama de casos y pequeños esquemas de como podría ser la UI
@Zaedlen @UndMe @daniel-diazl @pablopg99 #

**Comment by JuanCasado** [comment]
El boceto está muy muy guay, lo único que todo lo que sean imágenes súbelas en .png y adicionalmente si quieres en el documento editable del programa que uses, pero mola mucho aunque las habitaciones del juego tendrán que ser un poco más grandes jajajjaja, y pasa porfa en cuanto puedas el texto que tenías a ordena please @UndMe

**Comment by JuanCasado** [comment]
Perdona el docx no lo había visto jajajajajja, sorry @UndMe

**Comment by UndMe** [comment]
Acabo de subir ahora mismo en .PNG el boceto. Estoy haciendo otro de lo que pueden ser los NPC que estén sueltos por las habitaciones o el boss final de cada nivel.
Es a papel asique habría que ver la forma de implementarlo en el ordena, cuando lo tenga lo subo también.

**Comment by UndMe** [comment]
Acabo de subir ahora mismo un boceto de lo que podría ser el boss final de los niveles.
Cuando podáis echadle un ojo porque si os gusta la idea podría intentar pasarlo con photoshop a ordena y pintado quedaría bastante chulo.
Se podría también adjuntar a las fotos que van al final del documento de diseño.

**Comment by Zaedlen** [comment]
Vale, voy a añadir los nombres y los dnis y ya estaría terminado el documento.

**IMPORTANTE**
Lo dejo donde siempre: Documentacion>Diseño y mecánicas. La version word y la version pdf
Leedlo por favor a lo largo de la tarde y comentar aquí si falta algo, erratas, si algo está mal, etc..
Yo revisare esta issue y estaré disponible por si hay que discutir algo esta noche sobre las 22:00-22:30 aprox. A esa hora miaré que habeis puesto, contestaré si hay preguntas e intentaré dejar finiquitado el documento. La idea es dejar subida la versión final en ese momento.

**Comment by UndMe** [comment]
Me parece que ha quedado bastante bien el documento tal cual esta @Zaedlen 
Lo unico no entiendo muy bien la finalidad que tiene la pantalla de log in, osea en principio el juego es de un jugador, no es online ni nada entonces no haria falta tener que iniciar sesion.

Nose si me dara tiempo hoy, pero voy a intentar hacer un logo de lo que podria ser la pantalla de inicio al entrar al juego.

**Comment by JuanCasado** [comment]
El documento está muy guay, voy a poner en la wiki que tenemos el diseño y eso para que lo puede encontrar bien el Profe porque lo mismo cuando vaya a buscarlo se pierde por las carpetas en cualquier caso y para todos está en Documentación/Diseño_y_mecánicas/Documento_diseño.pdf

Lo del Log In me lo he sacado así un poco de la manga, lo podemos poner o no, la cosa es que si vamos a guardar los datos del personaje para continuar la partida terminado el juego es lo mismo, guardar el de un jugador que el de 20 y además eso nos permitiría incluir una opción de pruebas donde podamos configurar el mapa o los spawns con un entorno gráfico y que ahí solo podamos acceder nosotros con nuestros user y password

**Comment by UndMe** [comment]
Vale, me parece bien sobretodo la idea que has dicho de poder configurar el mapa y demas con una cuenta que pongamos como de root, no lo habia pensado y me gusta.

Otra cuestion, estoy haciendo un boceto de la imagen que podria ser la pantalla de inicio nada mas abrir el juego pero nose si me dara tiempo a tenerla antes de las 22:30 mas que nada porque salgo de trabajar a las 22. Lo digo porque alomejor a partir de las 23 podria tenerla y ya que esta incorporarla al documento de diseño pero claro tendriais que estar pendientes sobre esa hora para editarlo.
Sino yo lo subo y aunque no este en el documento lo tenemos ya para cuando toque hacerlo.

Porcierto cual es la wiki que dices que hay @JuanCasado .

**Comment by JuanCasado** [comment]
Vale, no te preocupes por la imagen, si puedes perfecto. Nosotros aproximadamente hasta el 23 no nos pongamos en serio del todo con el código por los exámenes y demás así que por lo menos hasta entonces ir teniendo las imágenes que sean más importantes para ir bien de tiempo.

La wiki es en las pestañas de gitHub la que pone wiki @UndMe

**Comment by UndMe** [comment]
Chicos acabo de subir el boceto de lo que podria ser el inicio del juego nada mas abrirlo. Si lo veis y quereis añadirlo al documento de diseño como veais.
